[package]
name = "smsg"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.32"
axum = { version = "0.8.9", features = ["ws"] }
rand = "0.10.1"
serde_json = "1.0.150"
rusmpp = { git = "https://github.com/Rusmpp/Rusmpp.git", rev = "d0ac3f6", features = ["tokio-codec", "tracing"] }
rusmppc = { git = "https://github.com/Rusmpp/Rusmpp.git", rev = "d0ac3f6" }

serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "net", "io-util", "time", "signal", "sync"] }
tokio-stream = { version = "0.1.18", features = ["net"] }
tokio-util = { version = "0.7.18", features = ["codec"] }
toml = "1.1.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
